// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_2x5_packed_valid_f16_biases_data[13] = {(float16_t)-0.472167969f,
                                                             (float16_t)-0.294433594f,
                                                             (float16_t)0.0155563354f,
                                                             (float16_t)-0.238769531f,
                                                             (float16_t)-0.200561523f,
                                                             (float16_t)0.446289062f,
                                                             (float16_t)0.0809936523f,
                                                             (float16_t)-0.0600585938f,
                                                             (float16_t)0.011390686f,
                                                             (float16_t)-0.104370117f,
                                                             (float16_t)0.264648438f,
                                                             (float16_t)-0.281982422f,
                                                             (float16_t)0.274658203f};
