// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_2x5_packed_valid_f32_biases_data[13] = {-0.472071886f,
                                                             -0.294338316f,
                                                             0.0155538311f,
                                                             -0.238823041f,
                                                             -0.20059298f,
                                                             0.44628942f,
                                                             0.0809641331f,
                                                             -0.0600630194f,
                                                             0.011389087f,
                                                             -0.10433989f,
                                                             0.264750779f,
                                                             -0.281998724f,
                                                             0.274591327f};
