// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k2_1d_opt_nhwc_f16_biases_data[8] = {(float16_t)0.259033203f,
                                                               (float16_t)-0.175292969f,
                                                               (float16_t)0.158813477f,
                                                               (float16_t)0.451416016f,
                                                               (float16_t)-0.141601562f,
                                                               (float16_t)0.0423583984f,
                                                               (float16_t)0.106140137f,
                                                               (float16_t)0.327392578f};
