// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_2x3_packed_valid_f16_biases_data[13] = {(float16_t)-0.315917969f,
                                                             (float16_t)0.0258789062f,
                                                             (float16_t)-0.014793396f,
                                                             (float16_t)0.10748291f,
                                                             (float16_t)0.0986938477f,
                                                             (float16_t)0.141967773f,
                                                             (float16_t)-0.478515625f,
                                                             (float16_t)-0.261474609f,
                                                             (float16_t)-0.158691406f,
                                                             (float16_t)-0.289306641f,
                                                             (float16_t)-0.204223633f,
                                                             (float16_t)-0.324707031f,
                                                             (float16_t)-0.16784668f};
