// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_k9_exact_six_f32_biases_data[10] = {0.302172124f,
                                                         0.218842641f,
                                                         -0.144026995f,
                                                         -0.287062734f,
                                                         0.0952828079f,
                                                         -0.212271616f,
                                                         0.382044315f,
                                                         -0.042331107f,
                                                         -0.493426621f,
                                                         0.120680928f};
