// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_k9_opt_f16_biases_data[12] = {(float16_t)0.197631836f,
                                                   (float16_t)0.0805664062f,
                                                   (float16_t)-0.0759887695f,
                                                   (float16_t)-0.0450134277f,
                                                   (float16_t)0.114257812f,
                                                   (float16_t)0.211791992f,
                                                   (float16_t)-0.406982422f,
                                                   (float16_t)-0.0775146484f,
                                                   (float16_t)-0.0905151367f,
                                                   (float16_t)0.431152344f,
                                                   (float16_t)0.217407227f,
                                                   (float16_t)0.0844116211f};
