// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_k7_opt_f32_biases_data[12] = {0.131382123f,
                                                   -0.288679272f,
                                                   0.336051822f,
                                                   0.408258796f,
                                                   -0.32366538f,
                                                   0.179365352f,
                                                   -0.261666238f,
                                                   -0.4556292f,
                                                   -0.107249446f,
                                                   -0.326092362f,
                                                   0.147249877f,
                                                   -0.412256777f};
