// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_k9_1d_opt_nhwc_f32_biases_data[8] =
    {0.0433179773f, -0.206883699f, -0.305968702f, 0.170379594f, 0.431116909f, 0.46774742f, -0.391821235f, 0.366706103f};
