// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_k9_exact_six_f16_biases_data[10] = {(float16_t)0.302246094f,
                                                         (float16_t)0.21887207f,
                                                         (float16_t)-0.144042969f,
                                                         (float16_t)-0.287109375f,
                                                         (float16_t)0.0952758789f,
                                                         (float16_t)-0.212280273f,
                                                         (float16_t)0.382080078f,
                                                         (float16_t)-0.0423278809f,
                                                         (float16_t)-0.493408203f,
                                                         (float16_t)0.120666504f};
