// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_k9_exact_six_f16_output_ref_data[60] = {
    (float16_t)-0.178344727f,   (float16_t)0.0293426514f,  (float16_t)0.940429688f,   (float16_t)0.473632812f,
    (float16_t)-0.931640625f,   (float16_t)-0.214477539f,  (float16_t)1.52148438f,    (float16_t)-0.602539062f,
    (float16_t)0.553222656f,    (float16_t)-0.0872802734f, (float16_t)-0.159912109f,  (float16_t)0.0159301758f,
    (float16_t)0.829101562f,    (float16_t)0.571777344f,   (float16_t)0.209594727f,   (float16_t)0.270996094f,
    (float16_t)0.696289062f,    (float16_t)-0.708496094f,  (float16_t)1.00195312f,    (float16_t)-0.682617188f,
    (float16_t)1.3984375f,      (float16_t)0.293212891f,   (float16_t)-0.140136719f,  (float16_t)0.420166016f,
    (float16_t)-0.594726562f,   (float16_t)0.145751953f,   (float16_t)0.853515625f,   (float16_t)0.150512695f,
    (float16_t)1.18554688f,     (float16_t)0.956054688f,   (float16_t)0.241333008f,   (float16_t)0.362060547f,
    (float16_t)-0.208618164f,   (float16_t)0.822753906f,   (float16_t)1.11132812f,    (float16_t)-0.15625f,
    (float16_t)-0.00429916382f, (float16_t)-0.719238281f,  (float16_t)-0.0255432129f, (float16_t)-0.0471801758f,
    (float16_t)0.17565918f,     (float16_t)0.337158203f,   (float16_t)0.264892578f,   (float16_t)0.366943359f,
    (float16_t)-1.52441406f,    (float16_t)-0.770019531f,  (float16_t)0.873046875f,   (float16_t)0.421386719f,
    (float16_t)0.548339844f,    (float16_t)1.17285156f,    (float16_t)0.319335938f,   (float16_t)-0.355712891f,
    (float16_t)-0.649902344f,   (float16_t)0.892578125f,   (float16_t)1.70214844f,    (float16_t)-1.875f,
    (float16_t)0.245605469f,    (float16_t)0.84375f,       (float16_t)-0.304199219f,  (float16_t)-1.4140625f};
