// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_2x3_packed_valid_f32_biases_data[13] = {-0.315796077f,
                                                             0.0258813724f,
                                                             -0.0147969751f,
                                                             0.107499957f,
                                                             0.0987071693f,
                                                             0.142011881f,
                                                             -0.478615999f,
                                                             -0.261384159f,
                                                             -0.15868178f,
                                                             -0.289399058f,
                                                             -0.204208046f,
                                                             -0.324627191f,
                                                             -0.167815343f};
