// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_2x3_opt_nhwc_f16_biases_data[8] = {(float16_t)0.176757812f,
                                                             (float16_t)0.0519714355f,
                                                             (float16_t)0.336914062f,
                                                             (float16_t)0.048248291f,
                                                             (float16_t)-0.382568359f,
                                                             (float16_t)0.427246094f,
                                                             (float16_t)0.161987305f,
                                                             (float16_t)0.0433349609f};
