// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_2x3_opt_nhwc_f16_weights_data[48] = {
    (float16_t)0.00438308716f, (float16_t)0.549316406f,   (float16_t)-0.02003479f,  (float16_t)0.231689453f,
    (float16_t)-0.0459899902f, (float16_t)-0.0878295898f, (float16_t)0.264404297f,  (float16_t)-0.356933594f,
    (float16_t)0.572753906f,   (float16_t)-0.244262695f,  (float16_t)0.614257812f,  (float16_t)0.494384766f,
    (float16_t)-0.489990234f,  (float16_t)-0.0985717773f, (float16_t)-0.571289062f, (float16_t)-0.321289062f,
    (float16_t)0.748046875f,   (float16_t)0.623046875f,   (float16_t)-0.63671875f,  (float16_t)0.551269531f,
    (float16_t)0.487060547f,   (float16_t)0.608886719f,   (float16_t)0.145507812f,  (float16_t)-0.440673828f,
    (float16_t)0.316894531f,   (float16_t)-0.640625f,     (float16_t)-0.123168945f, (float16_t)0.178588867f,
    (float16_t)0.551269531f,   (float16_t)-0.0176544189f, (float16_t)-0.364013672f, (float16_t)0.0316772461f,
    (float16_t)0.506347656f,   (float16_t)-0.572265625f,  (float16_t)0.432617188f,  (float16_t)0.557617188f,
    (float16_t)0.399658203f,   (float16_t)0.678710938f,   (float16_t)-0.665527344f, (float16_t)0.156494141f,
    (float16_t)-0.640136719f,  (float16_t)-0.391601562f,  (float16_t)0.234741211f,  (float16_t)0.429931641f,
    (float16_t)0.681152344f,   (float16_t)-0.232421875f,  (float16_t)0.749023438f,  (float16_t)0.0258636475f};
