// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_k5_1d_opt_nhwc_f32_biases_data[8] = {0.105042748f,
                                                               -0.000238595036f,
                                                               0.156424284f,
                                                               -0.162449881f,
                                                               -0.321100712f,
                                                               0.155216783f,
                                                               -0.292984605f,
                                                               0.250860184f};
