// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_k7_opt_f16_biases_data[12] = {(float16_t)0.131347656f,
                                                   (float16_t)-0.288574219f,
                                                   (float16_t)0.3359375f,
                                                   (float16_t)0.408203125f,
                                                   (float16_t)-0.323730469f,
                                                   (float16_t)0.179321289f,
                                                   (float16_t)-0.26171875f,
                                                   (float16_t)-0.455566406f,
                                                   (float16_t)-0.10723877f,
                                                   (float16_t)-0.326171875f,
                                                   (float16_t)0.147216797f,
                                                   (float16_t)-0.412353516f};
