// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_k9_opt_f32_biases_data[12] = {0.197617665f,
                                                   0.080592379f,
                                                   -0.0759784654f,
                                                   -0.0450253822f,
                                                   0.114230819f,
                                                   0.211743161f,
                                                   -0.406952322f,
                                                   -0.0775340945f,
                                                   -0.0905411169f,
                                                   0.431057602f,
                                                   0.21746622f,
                                                   0.084416844f};
