// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k5_1d_opt_nhwc_f16_biases_data[8] = {(float16_t)0.105041504f,
                                                               (float16_t)-0.000238537788f,
                                                               (float16_t)0.15637207f,
                                                               (float16_t)-0.162475586f,
                                                               (float16_t)-0.321044922f,
                                                               (float16_t)0.155273438f,
                                                               (float16_t)-0.29296875f,
                                                               (float16_t)0.250976562f};
