// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k5_1d_opt_nhwc_f16_weights_data[40] = {
    (float16_t)-0.651855469f,  (float16_t)-0.0819091797f, (float16_t)0.322998047f,  (float16_t)-0.534179688f,
    (float16_t)-0.487792969f,  (float16_t)-0.235839844f,  (float16_t)0.578125f,     (float16_t)0.532714844f,
    (float16_t)0.722167969f,   (float16_t)-0.462890625f,  (float16_t)0.472900391f,  (float16_t)0.460693359f,
    (float16_t)0.354492188f,   (float16_t)0.464355469f,   (float16_t)-0.141723633f, (float16_t)-0.255126953f,
    (float16_t)-0.619140625f,  (float16_t)-0.270507812f,  (float16_t)0.6875f,       (float16_t)-0.608398438f,
    (float16_t)0.717285156f,   (float16_t)0.470214844f,   (float16_t)-0.5703125f,   (float16_t)-0.0686645508f,
    (float16_t)-0.710449219f,  (float16_t)0.655761719f,   (float16_t)-0.138061523f, (float16_t)0.165771484f,
    (float16_t)-0.0224761963f, (float16_t)-0.103149414f,  (float16_t)0.354736328f,  (float16_t)-0.409667969f,
    (float16_t)0.00149917603f, (float16_t)-0.6484375f,    (float16_t)-0.536621094f, (float16_t)-0.101013184f,
    (float16_t)-0.264892578f,  (float16_t)0.624511719f,   (float16_t)-0.637695312f, (float16_t)-0.474121094f};
