// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_k5_batch2_rows2_tails_null_bias_f32_biases_data[11] =
    {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
