// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_k7_1d_opt_nhwc_f32_biases_data[8] = {0.474181622f,
                                                               0.284145892f,
                                                               -0.141065553f,
                                                               -0.0207226947f,
                                                               0.421290636f,
                                                               0.373412937f,
                                                               0.0911407396f,
                                                               -0.070867613f};
