// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k7_1d_opt_nhwc_f16_biases_data[8] = {(float16_t)0.474121094f,
                                                               (float16_t)0.284179688f,
                                                               (float16_t)-0.141113281f,
                                                               (float16_t)-0.0207214355f,
                                                               (float16_t)0.421386719f,
                                                               (float16_t)0.373291016f,
                                                               (float16_t)0.0911254883f,
                                                               (float16_t)-0.0708618164f};
