// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k7_1d_opt_nhwc_f16_weights_data[56] = {
    (float16_t)0.262207031f,   (float16_t)-0.666015625f,  (float16_t)-0.708984375f, (float16_t)0.681640625f,
    (float16_t)0.356201172f,   (float16_t)-0.0218048096f, (float16_t)0.0522766113f, (float16_t)-0.349365234f,
    (float16_t)0.0739746094f,  (float16_t)-0.393310547f,  (float16_t)-0.383544922f, (float16_t)0.509765625f,
    (float16_t)-0.459716797f,  (float16_t)-0.0635986328f, (float16_t)-0.292236328f, (float16_t)0.178100586f,
    (float16_t)-0.711425781f,  (float16_t)0.0754394531f,  (float16_t)0.516113281f,  (float16_t)0.595214844f,
    (float16_t)0.622558594f,   (float16_t)0.30859375f,    (float16_t)0.458496094f,  (float16_t)-0.572753906f,
    (float16_t)-0.690917969f,  (float16_t)0.474609375f,   (float16_t)-0.654296875f, (float16_t)0.141235352f,
    (float16_t)0.490722656f,   (float16_t)0.11920166f,    (float16_t)-0.117919922f, (float16_t)-0.141357422f,
    (float16_t)-0.0546569824f, (float16_t)-0.138916016f,  (float16_t)-0.174316406f, (float16_t)-0.563476562f,
    (float16_t)0.280273438f,   (float16_t)0.458740234f,   (float16_t)0.430664062f,  (float16_t)-0.366699219f,
    (float16_t)-0.206420898f,  (float16_t)-0.64453125f,   (float16_t)0.472900391f,  (float16_t)0.617675781f,
    (float16_t)0.343261719f,   (float16_t)-0.296142578f,  (float16_t)-0.268310547f, (float16_t)-0.679199219f,
    (float16_t)-0.276611328f,  (float16_t)-0.657226562f,  (float16_t)0.424560547f,  (float16_t)-0.0592041016f,
    (float16_t)0.16784668f,    (float16_t)0.387451172f,   (float16_t)-0.689453125f, (float16_t)0.224853516f};
