// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k9_1d_mult9_f16_input_data[60] = {
    (float16_t)-0.141357422f,  (float16_t)0.0189208984f,  (float16_t)-0.782714844f, (float16_t)0.957519531f,
    (float16_t)0.635742188f,   (float16_t)-0.168212891f,  (float16_t)-0.626464844f, (float16_t)0.193603516f,
    (float16_t)0.337646484f,   (float16_t)-0.327148438f,  (float16_t)0.270263672f,  (float16_t)0.672851562f,
    (float16_t)0.0617370605f,  (float16_t)0.829589844f,   (float16_t)-0.120605469f, (float16_t)-0.0872192383f,
    (float16_t)0.936523438f,   (float16_t)-0.0968017578f, (float16_t)-0.255126953f, (float16_t)-0.403564453f,
    (float16_t)-0.96484375f,   (float16_t)0.990234375f,   (float16_t)-0.223999023f, (float16_t)-0.661621094f,
    (float16_t)0.782714844f,   (float16_t)0.683105469f,   (float16_t)0.937988281f,  (float16_t)0.217163086f,
    (float16_t)-0.314453125f,  (float16_t)0.372070312f,   (float16_t)-0.73046875f,  (float16_t)-0.139404297f,
    (float16_t)0.478759766f,   (float16_t)0.96875f,       (float16_t)0.229736328f,  (float16_t)-0.400390625f,
    (float16_t)-0.549316406f,  (float16_t)-0.515625f,     (float16_t)-0.812011719f, (float16_t)0.974609375f,
    (float16_t)-0.229003906f,  (float16_t)0.0523071289f,  (float16_t)-0.224975586f, (float16_t)0.566894531f,
    (float16_t)0.544433594f,   (float16_t)-0.343505859f,  (float16_t)-0.4453125f,   (float16_t)0.971191406f,
    (float16_t)-0.933105469f,  (float16_t)-0.247802734f,  (float16_t)-0.882324219f, (float16_t)0.0866699219f,
    (float16_t)0.237182617f,   (float16_t)0.846679688f,   (float16_t)0.560058594f,  (float16_t)-0.208129883f,
    (float16_t)-0.0108795166f, (float16_t)0.512695312f,   (float16_t)0.302978516f,  (float16_t)0.580078125f};
