// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_k2_packed_valid_f32_biases_data[13] = {0.310311526f,
                                                            -0.0753023401f,
                                                            0.189955756f,
                                                            -0.19539912f,
                                                            0.329543591f,
                                                            -0.247785687f,
                                                            -0.351838738f,
                                                            0.00142807304f,
                                                            0.34711051f,
                                                            0.332104355f,
                                                            0.314265102f,
                                                            0.213371426f,
                                                            -0.374726772f};
