// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k9_1d_opt_nhwc_f16_biases_data[8] = {(float16_t)0.0433044434f,
                                                               (float16_t)-0.20690918f,
                                                               (float16_t)-0.305908203f,
                                                               (float16_t)0.170410156f,
                                                               (float16_t)0.431152344f,
                                                               (float16_t)0.467773438f,
                                                               (float16_t)-0.391845703f,
                                                               (float16_t)0.366699219f};
