// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k9_1d_opt_nhwc_f16_input_data[46] = {
    (float16_t)-0.478759766f, (float16_t)0.30859375f,    (float16_t)-0.962402344f, (float16_t)0.576660156f,
    (float16_t)0.056640625f,  (float16_t)0.666015625f,   (float16_t)-0.813476562f, (float16_t)0.405761719f,
    (float16_t)-0.190307617f, (float16_t)0.865234375f,   (float16_t)-0.737304688f, (float16_t)-0.818847656f,
    (float16_t)0.458007812f,  (float16_t)-0.581054688f,  (float16_t)0.270751953f,  (float16_t)0.840332031f,
    (float16_t)-0.124328613f, (float16_t)0.186523438f,   (float16_t)0.0863037109f, (float16_t)-0.171508789f,
    (float16_t)0.973144531f,  (float16_t)-0.425537109f,  (float16_t)0.220214844f,  (float16_t)-0.000186562538f,
    (float16_t)-0.192871094f, (float16_t)0.346679688f,   (float16_t)0.976074219f,  (float16_t)-0.744140625f,
    (float16_t)-0.414306641f, (float16_t)-0.735351562f,  (float16_t)-0.197875977f, (float16_t)-0.538574219f,
    (float16_t)-0.725585938f, (float16_t)0.819335938f,   (float16_t)-0.842773438f, (float16_t)0.363037109f,
    (float16_t)-0.794433594f, (float16_t)0.947265625f,   (float16_t)0.455566406f,  (float16_t)0.0746459961f,
    (float16_t)0.620605469f,  (float16_t)-0.626953125f,  (float16_t)-0.210693359f, (float16_t)-0.100891113f,
    (float16_t)-0.573730469f, (float16_t)-0.00664138794f};
