// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_2x3_opt_nhwc_f32_biases_data[8] = {0.176780254f,
                                                             0.0519823544f,
                                                             0.336893797f,
                                                             0.0482353605f,
                                                             -0.382641256f,
                                                             0.427238733f,
                                                             0.161996692f,
                                                             0.0433417037f};
