// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_k2_packed_valid_f16_biases_data[13] = {(float16_t)0.310302734f,
                                                            (float16_t)-0.0753173828f,
                                                            (float16_t)0.189941406f,
                                                            (float16_t)-0.19543457f,
                                                            (float16_t)0.329589844f,
                                                            (float16_t)-0.247802734f,
                                                            (float16_t)-0.351806641f,
                                                            (float16_t)0.00142765045f,
                                                            (float16_t)0.347167969f,
                                                            (float16_t)0.33203125f,
                                                            (float16_t)0.314208984f,
                                                            (float16_t)0.213378906f,
                                                            (float16_t)-0.374755859f};
