// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_k2_1d_opt_nhwc_f32_biases_data[8] =
    {0.259048373f, -0.175299168f, 0.158803597f, 0.451444f, -0.141610652f, 0.0423510969f, 0.106159784f, 0.327495992f};
