// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_k5_batch2_rows2_tails_null_bias_f16_biases_data[11] = {(float16_t)0.0f,
                                                                            (float16_t)0.0f,
                                                                            (float16_t)0.0f,
                                                                            (float16_t)0.0f,
                                                                            (float16_t)0.0f,
                                                                            (float16_t)0.0f,
                                                                            (float16_t)0.0f,
                                                                            (float16_t)0.0f,
                                                                            (float16_t)0.0f,
                                                                            (float16_t)0.0f,
                                                                            (float16_t)0.0f};
